robotpy/pyfrc

- lib/pyfrc/mains/cli_deploy.py
Do you think this is a good idea?
> Change working directory before running robot program.

- lib/pyfrc/sim/ui.py
Implemented voltage mode, %vbus mode, and follower mode. I believe implementing current mode, velocity mode, or position mode would require a physics engine.
> CAN did not correctly represent value on GUI based on control mode. 

- lib/pyfrc/physics/drivetrains.py
Adjusted reverse kinematic mecanum equation to take wheelbase dimensions into account.
> Adjusted reverse kinematic mecanum equation

- lib/pyfrc/sim/ui.py
Depends on https://github.com/robotpy/robotpy-wpilib/pull/180
> Support displaying all CAN input sensors

- lib/pyfrc/mains/cli_deploy.py
> Fix --in-place option

- .gitignore
project dir .idea and module file pyfrc.iml added to .gitignore file
> ignore project files for intellij idea and pycharm

- lib/pyfrc/robotpy/installer.py
<s>Like all good code, this is completely untested and unproven. </s> 
I don't have a robot to test on right now. I'll create a pull request for robotpy-wpilib as well to update its file.
> Fixed the IPv6 problem when deploying to the robot.

- lib/pyfrc/test_support/fake_time.py
This should probably fix the intermittent failure once and for all.
Ref: #81
> fake_time: Protect reading _child_threads dict

- lib/pyfrc/tests/docstring_test.py
Removes deprecated inspectargs
Adds checks for docstring and type hint
> Add to docstring_test

- lib/pyfrc/physics/core.py
I think this is clearer... any opinions?
> Wrap user thrown physics exception

- lib/pyfrc/config.py
- lib/pyfrc/configloader.py
- lib/pyfrc/mains/cli_sim.py
- lib/pyfrc/mains/cli_test.py
- lib/pyfrc/sim/robot_controller.py
- lib/pyfrc/sim/sim_manager.py
- lib/pyfrc/sim/ui.py
- lib/pyfrc/test_support/controller.py
- lib/pyfrc/tests/basic.py
- lib/pyfrc/tests/fuzz_test.py
- requirements.txt
- tests/test_tests.py
* Makes game-specific message user configurable
* Cycles autonomous mode through each of the game specific messages (no more blank messages)
* Only sets game specific message when autonomous starts (which is what the FMS says it does)
> Season-specific changes

- lib/pyfrc/tests/fuzz_test.py
It looks like nothing is actually currently setting has_source in the
hal_data dict.  Ignore those for now...
> fuzz_test: Fix fuzz_all

- lib/pyfrc/physics/drivetrains.py
- Allows retrieving optional data to use for setting up encoders
- Fixes #116
> physics: drivetrain functions are objects now

- lib/pyfrc/mains/cli_deploy.py
Haven't had a chance to test this yet, but putting this here in case someone else does get a chance.
> Make deploys more atomic

- docs/conf.py
- docs/physics.rst
- lib/pyfrc/physics/core.py
- lib/pyfrc/physics/drivetrains.py
- lib/pyfrc/physics/motor_cfgs.py
- lib/pyfrc/physics/tankmodel.py
- lib/pyfrc/physics/units.py
- requirements.txt
Tested it with robot code and some logging data from one of the robots I work with, and it's definitely better than what we have now. The output data is even vaguely believable.
The plan is to convert all existing physics examples to use this model, and perhaps get rid of the old drivetrain stuff in the future.
Based on paper at https://www.chiefdelphi.com/media/papers/3402 -- definitely wouldn't have been possible without their effort!
> Add realistic tank-drive model

- lib/pyfrc/mains/cli_deploy.py
> Delete /home/lvuser/py_new before deploy if exists

- .travis.yml
- setup.cfg
- setup.py
Not sure whether we should actually build wheels for pyfrc, but ¯\\\_(ツ)_/¯
> Fix building wheels

- lib/pyfrc/sim/field/user_renderer.py
Otherwise we spend time deleting elements that have already been deleted.
> UserRenderer: Clear stored elements on delete

- pyfrc/config.py
- pyfrc/mains/cli_undeploy.py
- setup.cfg
As requested, here it is. I think I covered, it all but I haven't been able to test it yet.
> Added a command to wipe the files on the RoboRIO. 

- pyfrc/mains/cli_create_physics.py
- pyfrc/physics/core.py
- Too many sim things need the original instance to work
@auscompgeek too ugly for us?
> Provide users an instance of their robot class

- pyfrc/mains/cli_deploy.py
- pyfrc/mains/cli_deploy_info.py
- setup.cfg
This is a little messy, but maybe promising?
> Alternative fix for #194: Use a deploy.json

- pyfrc/mains/cli_sim.py
- pyfrc/physics/core.py
- It's also a hack, but arguably a lesser evil than the prior hack
> Use a dynamic robot class to pass robot to physics

- pyfrc/mains/cli_add_tests.py
We have functioning robot tests now, right?
> Re-enable add-tests command

- pyfrc/test_support/pytest_plugin.py
Blocked on https://github.com/robotpy/robotpy-wpilib/pull/717
> Clear shuffleboard data after each test

- pyfrc/test_support/controller.py
On python 3.11 you get something like this:
```
>       self.drive.arcadeDrive(fwd, rot)
E       RuntimeError: HAL: A handle parameter was passed incorrectly: Channel 0
E       *** Do not reuse HAL objects in tests! This may occur if you stored a motor/sensor as a global or as a class variable outside of a method.
```
Not totally happy with the wording yet.
Inspired by @BerkeSinanYetkin's problem
> Provide better error messages if a user reuses a HAL object

- pyfrc/mains/cli_coverage.py
https://coverage.readthedocs.io/en/7.1.0/cmd.html#combining-data-files-coverage-combine
> cli_coverage: Add --parallel-mode
